spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bascrescer
    username: bascrescer
    password: bascrescer
  jpa:
    hibernate:
      ddl-auto: validate

server:
  error:
    include-message: always
    include-exception: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet: DEBUG
#    org.springframework.security: DEBUG
